steps:
    - id: "Install npm dependencies"
      name: "node:10.24.1"
      entrypoint: "npm"
      args: ["ci"]

    - id: "Run linter"
      name: "node:10.24.1"
      entrypoint: "npm"
      args: ["run", "lint"]
