steps:
    - id: "Install npm dependencies"
      name: "node:10.24.1"
      entrypoint: "npm"
      args: ["ci"]

    - id: "Run linter"
      name: "node:10.24.1"
      entrypoint: "npm"
      args: ["run", "lint"]

    - id: "Build static site files"
      name: "node:10.24.1"
      entrypoint: "npm"
      args: ["run", "build"]

    - id: "Deploy site"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: sh
      args:
          - -c
          - |
            sh ./scripts/deploy.sh
