steps:
    - id: "Install npm dependencies"
      name: "gcr.io/cloud-builders/npm"
      args: ["install"]

    - id: "Build static site files"
      name: "gcr.io/cloud-builders/npm"
      args: ["run", "build"]

    - id: "Deploy site"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: sh
      args:
          - -c
          - |
            sh ./scripts/deploy.sh
